apiVersion: v1
kind: ConfigMap
metadata:
  name: n8n-config
  namespace: n8n
data:
  DB_TYPE: postgresdb
  DB_POSTGRESDB_HOST: postgres
  DB_POSTGRESDB_PORT: "5432"
  N8N_HOST: "n8n.local"
  N8N_PORT: "5678"
  N8N_PROTOCOL: "http"
  EXECUTIONS_MODE: "queue"
  QUEUE_MODE: "redis"
  QUEUE_BULL_REDIS_HOST: "redis"
  N8N_BASIC_AUTH_ACTIVE: "true"
