apiVersion: batch/v1
kind: CronJob
metadata:
  name: paperless-db-backup
  namespace: paperless
spec:
  schedule: "0 3 * * *" # täglich um 3 Uhr
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: backup
              image: postgres:15
              env:
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: paperless-secret
                      key: db-password
              command:
                - /bin/sh
                - -c
                - |
                  pg_dump -h paperless-postgres-postgresql-ha-pgpool -U paperless -d paperless > /backup/paperless-$(date +%F).sql
              volumeMounts:
                - name: backup-volume
                  mountPath: /backup
          restartPolicy: OnFailure
          volumes:
            - name: backup-volume
              persistentVolumeClaim:
                claimName: backup-pvc
