apiVersion: v1
kind: Service
metadata:
  name: paperless
  namespace: paperless
spec:
  type: LoadBalancer
  selector:
    app: paperless
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
    - name: smb
      port: 445
      targetPort: 445
    - name: netbios
      port: 139
      targetPort: 139
    - name: sftp
      port: 2222
      targetPort: 2222
