apiVersion: v1
kind: Service
metadata:
  name: paperless
  namespace: paperless
spec:
  type: LoadBalancer
  selector:
    app: paperless
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
